name: nyc_taxi_analytics
version: "1.0.0"

profile: nyc_taxi_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]

target-path: target
clean-targets:
  - target
  - dbt_packages

require-dbt-version: [">=1.10.0", "<2.0.0"]

models:
  nyc_taxi_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

seeds:
  nyc_taxi_analytics:
    +schema: seeds
    taxi_zone_lookup:
      +column_types:
        LocationID: integer
